### PR TITLE
Search by uploader

### PR DESCRIPTION
**Pull request by melon095**
Search emotes by the uploader's username.

`-u, --uploader forsen`

### CODE REVIEW

**Review by brian6932 — APPROVED** [review]
Review was done through chat and patch files 4Head

**Comment by melon095** [comment]
whoops

**Review by brian6932 — APPROVED** [review]
Review was done through chat and patch files 4Head

**Comment by melon095** [comment]
image

**Comment by melon095** [comment]
Github, please can you keep my webp animated?

**Pull request merged**
